### ISSUE TITLE
ChatGPT.hpp: No such file or directory

### ISSUE THREAD

**Issue by ghost** [limengdu/XIAO-ESP32S3Sense-Speech2ChatGPT#2]
I cant compile the DEMO

I got the error "ChatGPT.hpp: No such file or directory"

I dont have this file! How can i solve it?

**Comment by limengdu** [comment]
https://github.com/limengdu/XIAO-ESP32S3Sense-Speech2ChatGPT/blob/main/libraries/ChatGPT_Client.zip
Please add this library to your Arduino environment.
